name: Scrape CSSBattle Solutions

on:
  schedule:
    - cron: "0 6 * * *"   # runs daily at 06:00 UTC
  workflow_dispatch:       # allow manual run

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run scraper
        run: node scripts/scraper.js

      - name: Upload all JSON artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cssbattle-solutions
          path: data/*.json
          retention-days: 7

      - name: Upload metadata separately
        uses: actions/upload-artifact@v4
        with:
          name: cssbattle-metadata
          path: data/targets-metadata.json
          retention-days: 7

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/
          git commit -m "chore: update solutions for $(date +%F)" || echo "No changes"
          git push
